/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\low_poly_room_2.glb --transform --output src/model-components/LowPolyRoom2.tsx --types 
Files: .\public\low_poly_room_2.glb [2.71MB] > C:\Users\aaron\Documents\GitHub\ChatVRM\src\model-components\low_poly_room_2-transformed.glb [595.83KB] (78%)
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Group, Object3DEventMap } from "three";

type ActionName = "Animation";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Chair: THREE.Mesh;
    Draw2: THREE.Mesh;
    Draw1: THREE.Mesh;
    Draw3: THREE.Mesh;
    Bed: THREE.Mesh;
    Object_34001: THREE.Mesh;
    Object_34001_1: THREE.Mesh;
    Lamp: THREE.Mesh;
    MonitorScreen: THREE.Mesh;
    Webcam: THREE.Mesh;
    PC: THREE.Mesh;
    Floor: THREE.Mesh;
    Object_44001: THREE.Mesh;
    Object_44001_1: THREE.Mesh;
    Billboard: THREE.Mesh;
    mesh_25003: THREE.Mesh;
    mesh_25003_1: THREE.Mesh;
  };
  materials: {
    ["LowPoly.001"]: THREE.MeshStandardMaterial;
    ["Rainbow.001"]: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    ["Screen.001"]: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
    PaletteMaterial004: THREE.MeshPhysicalMaterial;
    ["Floor.001"]: THREE.MeshStandardMaterial;
    PaletteMaterial005: THREE.MeshStandardMaterial;
    PaletteMaterial006: THREE.MeshStandardMaterial;
    ["trees.001"]: THREE.MeshPhysicalMaterial;
  };
  animations: GLTFAction[];
};

export function LowPolyRoom(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<Group<Object3DEventMap>>(null);
  const { nodes, materials, animations } = useGLTF(
    "/low_poly_room_2-transformed.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Chair_23" position={[-0.896, 0.397, 0.815]}>
            <mesh
              name="Chair"
              geometry={nodes.Chair.geometry}
              material={materials["LowPoly.001"]}
              position={[0, -0.214, 0]}
            />
          </group>
          <group name="Cube006_0" position={[-1.407, 0.567, 1.454]}>
            <mesh
              name="Draw2"
              geometry={nodes.Draw2.geometry}
              material={materials["LowPoly.001"]}
            />
          </group>
          <group name="Cube007_1" position={[-1.394, 0.755, 1.454]}>
            <mesh
              name="Draw1"
              geometry={nodes.Draw1.geometry}
              material={materials["LowPoly.001"]}
            />
          </group>
          <group name="Cube009_2" position={[-1.407, 0.366, 1.454]}>
            <mesh
              name="Draw3"
              geometry={nodes.Draw3.geometry}
              material={materials["LowPoly.001"]}
            />
          </group>
          <group
            name="Cube011_5"
            position={[-0.896, 0.397, 0.815]}
            rotation={[0, 0.052, 0]}
          />
          <group name="Shelves002_39" position={[-1.704, 0.833, -1.42]} />
        </group>
        <mesh
          name="Bed"
          geometry={nodes.Bed.geometry}
          material={materials["LowPoly.001"]}
          position={[-0.424, 0.536, -1.826]}
        />
        <group name="Keyboard" position={[-1.447, 0.929, 0.727]}>
          <mesh
            name="Object_34001"
            geometry={nodes.Object_34001.geometry}
            material={materials["Rainbow.001"]}
          />
          <mesh
            name="Object_34001_1"
            geometry={nodes.Object_34001_1.geometry}
            material={materials.PaletteMaterial001}
          />
        </group>
        <mesh
          name="Lamp"
          geometry={nodes.Lamp.geometry}
          material={materials.PaletteMaterial002}
          position={[-1.448, 1.354, 1.722]}
          rotation={[-1.746, 0.848, -1.387]}
        />
        <mesh
          name="MonitorScreen"
          geometry={nodes.MonitorScreen.geometry}
          material={materials["Screen.001"]}
          position={[-1.77, 1.106, 0.769]}
        />
        <mesh
          name="Webcam"
          geometry={nodes.Webcam.geometry}
          material={materials.PaletteMaterial003}
          position={[-1.77, 1.106, 0.769]}
        />
        <mesh
          name="PC"
          geometry={nodes.PC.geometry}
          material={materials.PaletteMaterial004}
          position={[-1.604, 0.484, 0.161]}
        />
        <mesh
          name="Floor"
          geometry={nodes.Floor.geometry}
          material={materials["Floor.001"]}
          position={[-1.347, 1.173, 0.409]}
        />
        <group name="Powerboard" position={[-1.95, 0.169, 0.769]}>
          <mesh
            name="Object_44001"
            geometry={nodes.Object_44001.geometry}
            material={materials.PaletteMaterial005}
          />
          <mesh
            name="Object_44001_1"
            geometry={nodes.Object_44001_1.geometry}
            material={materials.PaletteMaterial006}
          />
        </group>
        <mesh
          name="Billboard"
          geometry={nodes.Billboard.geometry}
          material={materials["trees.001"]}
          position={[-9.023, 0.477, -2.995]}
          scale={1.343}
        />
        <group
          name="Speaker"
          position={[-1.712, 1.108, 0.24]}
          rotation={[0, -Math.PI / 6, 0]}
        >
          <mesh
            name="mesh_25003"
            geometry={nodes.mesh_25003.geometry}
            material={materials.PaletteMaterial001}
            morphTargetDictionary={nodes.mesh_25003.morphTargetDictionary}
            morphTargetInfluences={nodes.mesh_25003.morphTargetInfluences}
          />
          <mesh
            name="mesh_25003_1"
            geometry={nodes.mesh_25003_1.geometry}
            material={materials["LowPoly.001"]}
            morphTargetDictionary={nodes.mesh_25003_1.morphTargetDictionary}
            morphTargetInfluences={nodes.mesh_25003_1.morphTargetInfluences}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/low_poly_room_2-transformed.glb");
