/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\low_poly_room_4.glb --output src/model-components/LowPolyRoom4.tsx --types 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type ActionName = "Animation";
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Billboard: THREE.Mesh;
    Bookshelf: THREE.Mesh;
    Books: THREE.Mesh;
    PotPlant: THREE.Mesh;
    Printer: THREE.Mesh;
    Desk: THREE.Mesh;
    Draw1: THREE.Mesh;
    Draw2: THREE.Mesh;
    Draw3: THREE.Mesh;
    Object_34001: THREE.Mesh;
    Object_34001_1: THREE.Mesh;
    Object_34001_2: THREE.Mesh;
    Object_9001: THREE.Mesh;
    Object_9001_1: THREE.Mesh;
    Monitor: THREE.Mesh;
    MonitorScreen: THREE.Mesh;
    Object_14001: THREE.Mesh;
    Object_14001_1: THREE.Mesh;
    Object_14001_2: THREE.Mesh;
    Mouse: THREE.Mesh;
    Mug: THREE.Mesh;
    Object_47001: THREE.Mesh;
    Object_47001_1: THREE.Mesh;
    Object_47001_2: THREE.Mesh;
    TissueBox: THREE.Mesh;
    SpeakerL: THREE.Mesh;
    mesh_25003: THREE.Mesh;
    mesh_25003_1: THREE.Mesh;
    Floor: THREE.Mesh;
    Bed: THREE.Mesh;
    Bin: THREE.Mesh;
    Chair: THREE.Mesh;
    Object_44001: THREE.Mesh;
    Object_44001_1: THREE.Mesh;
    Object_44001_2: THREE.Mesh;
    Rug: THREE.Mesh;
    Wall: THREE.Mesh;
    Blinds: THREE.Mesh;
    Glass: THREE.Mesh;
    Heater: THREE.Mesh;
  };
  materials: {
    ["trees.001"]: THREE.MeshPhysicalMaterial;
    ["LowPoly.001"]: THREE.MeshStandardMaterial;
    ["GlowB.001"]: THREE.MeshStandardMaterial;
    ["Rainbow.001"]: THREE.MeshStandardMaterial;
    ["GlowY.001"]: THREE.MeshStandardMaterial;
    ["Screen.001"]: THREE.MeshStandardMaterial;
    ["material.001"]: THREE.MeshStandardMaterial;
    ["Glass.001"]: THREE.MeshPhysicalMaterial;
    ["Floor.001"]: THREE.MeshStandardMaterial;
    ["GlowG.001"]: THREE.MeshStandardMaterial;
    ["GlowR.001"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function LowPolyRoom(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/low_poly_room_4.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {/* Billboard */}
        <mesh
          geometry={nodes.Billboard.geometry}
          material={materials["trees.001"]}
          position={[-9.023, 2.995, 0.477]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.343}
          userData={{ selectable: true }}
          name="BILLBOARD"
        />

        {/* Bookshelf and its children */}
        <mesh
          geometry={nodes.Bookshelf.geometry}
          material={materials["LowPoly.001"]}
          position={[-1.712, 1.537, 1.238]}
          rotation={[Math.PI / 2, 0, 0]}
          userData={{ selectable: true }}
          name="BOOKSHELF"
        >
          <mesh
            geometry={nodes.Books.geometry}
            material={materials["LowPoly.001"]}
            position={[0.018, 0.251, -0.544]}
            userData={{ selectable: true }}
            name="BOOKS"
          />
          <mesh
            geometry={nodes.PotPlant.geometry}
            material={materials["LowPoly.001"]}
            position={[0.008, 0.15, 0.36]}
            userData={{ selectable: true }}
            name="POT_PLANT"
          />
          <mesh
            geometry={nodes.Printer.geometry}
            material={materials["LowPoly.001"]}
            position={[0.008, -0.366, 0.109]}
            userData={{ selectable: true }}
            name="PRINTER"
          />
        </mesh>

        {/* Desk and its children */}
        <mesh
          geometry={nodes.Desk.geometry}
          material={materials["LowPoly.001"]}
          position={[-1.627, -0.793, 0.909]}
          rotation={[Math.PI / 2, 0, 0]}
          userData={{ selectable: true }}
          name="DESK"
        >
          <mesh
            geometry={nodes.Draw1.geometry}
            material={materials["LowPoly.001"]}
            position={[0.233, -0.154, 0.661]}
            userData={{ selectable: true }}
            name="DRAWER1"
          />
          <mesh
            geometry={nodes.Draw2.geometry}
            material={materials["LowPoly.001"]}
            position={[0.219, -0.342, 0.661]}
            userData={{ selectable: true }}
            name="DRAWER2"
          />
          <mesh
            geometry={nodes.Draw3.geometry}
            material={materials["LowPoly.001"]}
            position={[0.219, -0.543, 0.661]}
            userData={{ selectable: true }}
            name="DRAWER3"
          />
          <group
            position={[0.179, 0.02, 0.021]}
            userData={{ selectable: true }}
            name="KEYBOARD"
          >
            <mesh
              geometry={nodes.Object_34001.geometry}
              material={materials["GlowB.001"]}
            />
            <mesh
              geometry={nodes.Object_34001_1.geometry}
              material={materials["LowPoly.001"]}
            />
            <mesh
              geometry={nodes.Object_34001_2.geometry}
              material={materials["Rainbow.001"]}
            />
          </group>
          <group
            position={[0.179, 0.445, 0.929]}
            rotation={[-1.746, 0.848, -1.387]}
            userData={{ selectable: true }}
            name="LAMP"
          >
            <mesh
              geometry={nodes.Object_9001.geometry}
              material={materials["GlowY.001"]}
            />
            <mesh
              geometry={nodes.Object_9001_1.geometry}
              material={materials["LowPoly.001"]}
            />
          </group>
          <mesh
            geometry={nodes.Monitor.geometry}
            material={materials["LowPoly.001"]}
            position={[-0.145, 0.178, -0.024]}
            userData={{ selectable: true }}
            name="MONITOR"
          >
            <mesh
              geometry={nodes.MonitorScreen.geometry}
              material={materials["Screen.001"]}
              position={[0.02, 0.17, 0]}
            />
            <group position={[0.04, 0.426, 0.016]}>
              <mesh
                geometry={nodes.Object_14001.geometry}
                material={materials["material.001"]}
              />
              <mesh
                geometry={nodes.Object_14001_1.geometry}
                material={materials["GlowB.001"]}
              />
              <mesh
                geometry={nodes.Object_14001_2.geometry}
                material={materials["LowPoly.001"]}
              />
            </group>
          </mesh>
          <mesh
            geometry={nodes.Mouse.geometry}
            material={materials["LowPoly.001"]}
            position={[0.114, 0.021, -0.388]}
            userData={{ selectable: true }}
            name="MOUSE"
          />
          <mesh
            geometry={nodes.Mug.geometry}
            material={materials["LowPoly.001"]}
            position={[0.112, 0.003, 0.493]}
            userData={{ selectable: true }}
            name="MUG"
          />
          <group
            position={[0.023, -0.425, -0.632]}
            userData={{ selectable: true }}
            name="COMPUTER"
          >
            <mesh
              geometry={nodes.Object_47001.geometry}
              material={materials["LowPoly.001"]}
            />
            <mesh
              geometry={nodes.Object_47001_1.geometry}
              material={materials["GlowB.001"]}
            />
            <mesh
              geometry={nodes.Object_47001_2.geometry}
              material={materials["Glass.001"]}
            />
          </group>
          <mesh
            geometry={nodes.TissueBox.geometry}
            material={materials["LowPoly.001"]}
            position={[-0.018, 0.051, -0.826]}
            userData={{ selectable: true }}
            name="TISSUE_BOX"
          />
          <mesh
            name="SPEAKER_L"
            geometry={nodes.SpeakerL.geometry}
            material={materials["LowPoly.001"]}
            morphTargetDictionary={nodes.SpeakerL.morphTargetDictionary}
            morphTargetInfluences={nodes.SpeakerL.morphTargetInfluences}
            position={[-0.081, 0.211, 0.537]}
            rotation={[0, -Math.PI / 6, 0]}
            userData={{ selectable: true }}
          />
          <group
            position={[-0.081, 0.188, -0.551]}
            rotation={[0, -Math.PI / 6, 0]}
            userData={{ selectable: true }}
            name="SPEAKER_R"
          >
            <mesh
              name="mesh_25003"
              geometry={nodes.mesh_25003.geometry}
              material={materials["GlowB.001"]}
              morphTargetDictionary={nodes.mesh_25003.morphTargetDictionary}
              morphTargetInfluences={nodes.mesh_25003.morphTargetInfluences}
            />
            <mesh
              name="mesh_25003_1"
              geometry={nodes.mesh_25003_1.geometry}
              material={materials["LowPoly.001"]}
              morphTargetDictionary={nodes.mesh_25003_1.morphTargetDictionary}
              morphTargetInfluences={nodes.mesh_25003_1.morphTargetInfluences}
            />
          </group>
        </mesh>

        {/* Floor and its children */}
        <mesh
          geometry={nodes.Floor.geometry}
          material={materials["Floor.001"]}
          position={[0.625, -0.335, 0.164]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes.Bed.geometry}
            material={materials["LowPoly.001"]}
            position={[-1.026, 0.309, -2.165]}
            userData={{ selectable: true }}
            name="BED"
          />
          <mesh
            geometry={nodes.Bin.geometry}
            material={materials["LowPoly.001"]}
            position={[-2.342, 0.189, -0.846]}
            userData={{ selectable: true }}
            name="BIN"
          />
          <mesh
            geometry={nodes.Chair.geometry}
            material={materials["LowPoly.001"]}
            position={[-1.521, 0.018, 0.48]}
            userData={{ selectable: true }}
            name="CHAIR"
          />
          <group
            position={[-2.575, 0.005, 0.434]}
            userData={{ selectable: true }}
            name="POWER_SOCKET"
          >
            <mesh
              geometry={nodes.Object_44001.geometry}
              material={materials["LowPoly.001"]}
            />
            <mesh
              geometry={nodes.Object_44001_1.geometry}
              material={materials["GlowG.001"]}
            />
            <mesh
              geometry={nodes.Object_44001_2.geometry}
              material={materials["GlowR.001"]}
            />
          </group>
          <mesh
            geometry={nodes.Rug.geometry}
            material={materials["LowPoly.001"]}
            position={[-0.625, 0.008, -0.27]}
            userData={{ selectable: true }}
            name="RUG"
          />
        </mesh>

        {/* Wall and its children */}
        <mesh
          geometry={nodes.Wall.geometry}
          material={materials["LowPoly.001"]}
          position={[-0.497, 0.12, 0.681]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            geometry={nodes.Blinds.geometry}
            material={materials["LowPoly.001"]}
            position={[-1.454, 1.355, 0.818]}
          />
          <mesh
            geometry={nodes.Glass.geometry}
            material={materials["Glass.001"]}
            position={[-1.503, 1.055, 0.818]}
          />
          <mesh
            geometry={nodes.Heater.geometry}
            material={materials["LowPoly.001"]}
            position={[-1.373, -0.149, 2.205]}
            userData={{ selectable: true }}
            name="HEATER"
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/low_poly_room_4.glb");
